export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_WITHOUT_ACCOUNT = 'LOGIN_WITHOUT_ACCOUNT';

export const SELECT_PARKING = 'SELECT_PARKING';
export const DESELECT_PARKING = 'DESELECT_PARKING';

export const EXPAND_DETAILS = 'EXPAND_DETAILS';
export const HIDE_DETAILS = 'HIDE_DETAILS';

